language: node_js
sudo: false
node_js:
- 10
- 12
cache:
  npm: false
script:
- npm run build
- npm run test-unit-travis || travis_terminate 1
- npm run check-packages
after_success:
- npm run report-coverage
deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 12
    repo: ibm-cloud-security/security-advisor-sdk-node
